package pojos;
// Generated 22-abr-2014 18:45:34 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Conocimientos generated by hbm2java
 */
public class Conocimientos  implements java.io.Serializable {


     private Integer idConocimiento;
     private String nombre;
     private Set<Empleado> empleados;
     

    public Set getEmpleados() {
        return empleados;
    }

    public void setEmpleados(Set empleados) {
        this.empleados = empleados;
    }

    public Conocimientos() {
    }

	
    public Conocimientos(String nombre) {
        this.nombre = nombre;
    }
    public Conocimientos(String nombre, Set empleadoConocimientos) {
       this.nombre = nombre;
       this.empleados = empleadoConocimientos;
    }
   
    public Integer getIdConocimiento() {
        return this.idConocimiento;
    }
    
    public void setIdConocimiento(Integer idConocimiento) {
        this.idConocimiento = idConocimiento;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
   




}


